version: "3.9"
   
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: django 
    depends_on:
      - pg


  redis:
    image: redis:alpine
    container_name: redis


  celery:
    container_name: celery 
    command: celery -A project worker -l info 
    volumes:
      - .:/app
    depends_on:
      - redis
      - web 
    restart: always 
    build:
      context: .

  pg:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: