# Generated by Django 3.2 on 2022-07-23 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('type', models.CharField(choices=[('Home', 'Home'), ('office', 'office'), ('Bussines', 'Bussines'), ('Acadeny', 'Acadenyw'), ('Others', 'Others')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserPhone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('office', 'office'), ('Bussines', 'Bussines'), ('Acadeny', 'Acadenyw'), ('Others', 'Others')], max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('cauntry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cauntry', to='settings.cauntry')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_city', to='settings.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserAddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
