# Generated by Django 3.2 on 2022-08-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_video_url'),
        ('accounts', '0004_auto_20220720_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_products', to='products.Product'),
        ),
    ]
