# Generated by Django 3.2 on 2022-09-16 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.generate_code


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0004_auto_20220916_1654'),
        ('products', '0011_auto_20220916_1654'),
        ('accounts', '0005_profile_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default=utils.generate_code.generaste_code, max_length=8, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code_used',
            field=models.BooleanField(default=False, verbose_name='كود مستخدم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_products', to='products.Product', verbose_name='المفضله'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='البروفايل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_city', to='settings.city', verbose_name='المدينه'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_country', to='settings.country', verbose_name='الدوله'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='region',
            field=models.CharField(max_length=50, verbose_name='المنطقه'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=50, verbose_name='الولايه'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.CharField(max_length=50, verbose_name='الشارع'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Bussines', 'Bussines'), ('Academy', 'Academy'), ('Others', 'Others')], max_length=10, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAddress', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Bussines', 'Bussines'), ('Academy', 'Academy'), ('Others', 'Others')], max_length=10, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPhone', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
