# Generated by Django 3.2 on 2022-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221018_1306'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cauntry',
            new_name='Country',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Cauntries'},
        ),
    ]
