# Generated by Django 3.2 on 2022-09-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_city', to='settings.country', verbose_name='الدوله'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.CharField(max_length=300, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fb_link',
            field=models.URLField(blank=True, null=True, verbose_name='fb_link'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ins_link',
            field=models.URLField(blank=True, null=True, verbose_name='ins_link'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tw_link',
            field=models.URLField(blank=True, null=True, verbose_name='tw_link'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
