# Generated by Django 3.2 on 2022-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='banner/')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
