# Generated by Django 3.2 on 2022-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartorder_cartorderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderdetail',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
