# Generated by Django 3.2 on 2022-09-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartorderdetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderdetail',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartorderdetail',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartorderdetail',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
