# Generated by Django 3.2 on 2022-09-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220906_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='order_time',
        ),
        migrations.AlterField(
            model_name='cartorderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='orders.cartorder', verbose_name='cart_detail'),
        ),
    ]
