# Generated by Django 3.2 on 2022-08-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220819_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='order_time',
        ),
    ]
