# Generated by Django 3.2 on 2022-09-16 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.generate_code


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220916_1654'),
        ('orders', '0007_auto_20220819_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='code',
            field=models.CharField(default=utils.generate_code.generaste_code, max_length=8, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Completed', 'Completed')], max_length=10, verbose_name='حاله الطلب '),
        ),
        migrations.AlterField(
            model_name='cartorderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='orders.cartorder', verbose_name='تفاصيل الطلب '),
        ),
        migrations.AlterField(
            model_name='cartorderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_product', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=utils.generate_code.generaste_code, max_length=8, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Recieved', 'Recieved'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=10, verbose_name='حاله الطلب '),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الطلب '),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='orders.order', verbose_name='تفاصيل الطلب '),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.FloatField(verbose_name='الكميه'),
        ),
    ]
