# Generated by Django 3.2 on 2022-10-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220819_1837'),
        ('orders', '0007_auto_20220906_0502'),
    ]

    operations = [
    ]
