# Generated by Django 3.2 on 2022-07-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='', upload_to='brand/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
