# Generated by Django 3.2 on 2022-10-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220720_1450'),
        ('products', '0006_alter_product_brand'),
        ('products', '0011_auto_20220916_1654'),
    ]

    operations = [
    ]
